//// CCDInterpolate.H
//// Header autogenerated by MJEngine automation tools
//// WARNING: Do not modify autogenerated comments, automation 
//// tools depend on them.
//
//// Edition author: mzaldivar
//
//#pragma once
//#include "Component.h"
//#include "VQS.h"
//#include <vector>
//
//class FollowMeComponent;
//class TransformComponent;
//class CCDInterpolate : public Component
//{
//private:
//	// Start Private properties list
//
//		// TODO - declare private members
//	FollowMeComponent* ccd_solver;
//	double t; // from 0 to 1;
//	int i;
//
//	//TransformComponent* ownerTrans;
//	// End Private properties list
//	
//	// Start private user defined functions
//
//		// TODO - declare user defined private functions
//
//	// End private user defined functions
//
//public:
//
//	// Start Public properties list
//
//		// TODO - declare public members
//
//	// End Private properties list
//
//	CCDInterpolate();
//	~CCDInterpolate();
//
//	// Start implementation functions
//	bool Init();
//	void Update();
//	void HandleEvent(const Event* const evt);
//	// End implementation functions
//
//	// Start public user defined functions
//
//		// TODO - declare user defined public functions
//
//	// End public user defined functions
//};
