// LineComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"

class TransformComponent;
class GameObject;
class GLObject;
class LineComponent : public Component
{
private:
	// Start Private properties list

		// TODO - declare private members
	GameObject* owner;
	GameObject* ownerParent;
	TransformComponent* ownerTrans;
	TransformComponent* ownerParentTrans;


	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions

	// End private user defined functions

public:

	// Start Public properties list

		// TODO - declare public members

	// End Private properties list

	LineComponent();
	~LineComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void Destroy();
	void CompleteExtraSetup();
	// End implementation functions

	// Start public user defined functions

		// TODO - declare user defined public functions

	// End public user defined functions
};
