// LocalLightMoverComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"

class TransformComponent;
class LocalLightMoverComponent : public Component
{
private:
	// Start Private properties list

		// TODO - declare private members
	TransformComponent* transform;

	float moveX;
	float moveY;
	float moveZ = 0;

	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions

	// End private user defined functions

public:

	// Start Public properties list

		// TODO - declare public members

	// End Private properties list

	LocalLightMoverComponent();
	~LocalLightMoverComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void Serialize(std::istringstream* objcontentStream);
	// End implementation functions

	// Start public user defined functions

		// TODO - declare user defined public functions

	// End public user defined functions
};
