// MoveAlongPathComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"

#include <vector>
#include <glm.hpp>

class Spline;
class TransformComponent;
class MoveAlongPathComponent : public Component
{
private:
	// Start Private properties list

		// TODO - declare private members
	Spline* spline;
	TransformComponent* ownerTrans;


	int dummy_i = 0;
	bool moving;
	glm::vec3 lastOffsetCP;
	//double distanceCovered = 0.0000;
	// currentVelocity = 0.0000;
	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions

	// End private user defined functions
	std::vector<float> debugAngles;
public:

	// Start Public properties list

		// TODO - declare public members

	// End Private properties list

	MoveAlongPathComponent();
	~MoveAlongPathComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void Destroy();
	void HandleEvent(const Event* const evt);
	// End implementation functions

	// Start public user defined functions
	Spline* GetCurvePath() { return spline; }
		// TODO - declare user defined public functions

	// End public user defined functions
};
