// Move3DComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"
class TransformComponent;
class Move3DComponent : public Component
{
private:
	// Start Private properties list
	TransformComponent* transform;
	float angleX;
	float angleY;
	float angleZ;

	float moveX;
	float moveY;
	float moveZ = 0;

	bool move;
		// TODO - declare private members

	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions

	// End private user defined functions

public:

	// Start Public properties list

		// TODO - declare public members

	// End Private properties list

	Move3DComponent();
	~Move3DComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void Destroy();
	// End implementation functions

	// Start public user defined functions

		// TODO - declare user defined public functions

	// End public user defined functions
};
