#pragma once

#include "Component.h"

class TransformComponent;

class Move2DComponent : public Component
{

private:
	TransformComponent* transform;

public:
	Move2DComponent();
	~Move2DComponent();

	// Autogenerated by MJEngine automation tools
	// Start implementation functions
	bool Init();
	void Update();
	void Destroy();
	void HandleEvent(const Event* const evt);
	// End implementation functions
};

