// SplinePathGeneratorComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"
#include "Event.h"
#include <vector>

class RayPlaneIntersectEvaluatorComponent;
class Spline;
class GameObject;
class SplinePathGeneratorComponent : public Component
{
private:
	// Start Private properties list

		// TODO - declare private members
	RayPlaneIntersectEvaluatorComponent* rayCaster;
	Spline* spline;
	std::vector<GameObject*> cpGOs;
	bool canCreateCPs = false;
	bool pathExists;
	bool msgSent = false;
	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions
	void eraseCurve();
	// End private user defined functions

public:

	// Start Public properties list

		// TODO - declare public members

	// End Private properties list

	SplinePathGeneratorComponent();
	~SplinePathGeneratorComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void HandleEvent(const Event* const evt);
	void Destroy();
	// End implementation functions

	// Start public user defined functions

		// TODO - declare user defined public functions

	// End public user defined functions
};
