// UIUpdaterComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"
#include "UIManager.h"

class TransformComponent;
class LightPointComponent;
class Event;
class UIUpdaterComponent : public Component
{
private:
	// Start Private properties list

		// TODO - declare private members
	bool pushed;
	ImVec4* vec;
	ImVec4* rot;
	ImVec4* sca;
	ImVec4* lightColor;



	TransformComponent* trans;
	LightPointComponent* lightComp;

	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions

	// End private user defined functions

public:

	// Start Public properties list

		// TODO - declare public members

	// End Private properties list

	UIUpdaterComponent();
	~UIUpdaterComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void Destroy();
	void HandleEvent(const Event* const evt);
	// End implementation functions

	// Start public user defined functions

		// TODO - declare user defined public functions

	// End public user defined functions
};
