// Volume3DComponent.H
// Header autogenerated by MJEngine automation tools
// WARNING: Do not modify autogenerated comments, automation 
// tools depend on them.

// Edition author: mzaldivar

#pragma once
#include "Component.h"
#include "glm.hpp"

class TransformComponent;
class Transform;
class GameObject;

class Volume3DComponent : public Component
{
private:
	// Start Private properties list

		// TODO - declare private members
	Transform* trans;
	TransformComponent* transLoc;
	
	GameObject* ball;
	Transform* ballTrans;
	TransformComponent* ballTransform;


	// End Private properties list
	
	// Start private user defined functions

		// TODO - declare user defined private functions

	// End private user defined functions

public:

	// Start Public properties list

		// TODO - declare public members
	bool activateVolume;
	// End Private properties list

	Volume3DComponent();
	~Volume3DComponent();

	// Start implementation functions
	bool Init();
	void Update();
	void HandleEvent(const Event* const evt);
	void CompleteExtraSetup();
	// End implementation functions

	// Start public user defined functions

	bool isCloseEnough(glm::vec3 objLocation);
	bool computeVolumeEars(glm::vec3 ballPos, glm::vec3 ballVelo,
		glm::vec3 userHead, glm::vec3 userForward,
		float& leftEarvolume, float& rightEarVolume);
		// TODO - declare user defined public functions

	// End public user defined functions
};
